// Generated by CoffeeScript 1.9.3
(function() {
  var dox_coffee;

  module.exports = require('./dox');

  dox_coffee = require('./dox_coffee');

  module.exports.parseCommentsCoffee = dox_coffee.parseCommentsCoffee;

  module.exports.parseCodeContextCoffee = dox_coffee.parseCodeContextCoffee;

}).call(this);
