// Generated by CoffeeScript 1.10.0
(function() {
  exports.escape = function(html) {
    return String(html).replace(/&(?!\w+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  };

}).call(this);
