// Generated by CoffeeScript 1.7.1
(function() {
  var CodeContext, Comment, Tag;

  Tag = (function() {
    function Tag() {}

    return Tag;

  })();

  CodeContext = (function() {
    function CodeContext() {}

    return CodeContext;

  })();

  Comment = (function() {
    function Comment() {}

    return Comment;

  })();

}).call(this);
