// Generated by CoffeeScript 1.9.3
(function() {
  var Plugin;

  Plugin = (function() {
    function Plugin() {}

    Plugin.prototype.onComment = function(comment) {};

    return Plugin;

  })();

}).call(this);
