// Generated by CoffeeScript 2.4.1
//#
// Plugin interface
var Plugin;

Plugin = (function() {
  class Plugin {
    //#
    // Called for each comment of sources before processing tags.
    // @param {Comment} comment
    onComment(comment) {}

  };

  //#
  // External types supported by this plugin.
  Plugin.prototype.externalTypes = {};

  return Plugin;

}).call(this);
