// Generated by CoffeeScript 1.9.3
(function() {
  var CodeContext, Comment, Content, Options, Result, Tag;

  Options = (function() {
    function Options() {}

    return Options;

  })();

  Content = (function() {
    function Content() {}

    return Content;

  })();

  Tag = (function() {
    function Tag() {}

    return Tag;

  })();

  CodeContext = (function() {
    function CodeContext() {}

    return CodeContext;

  })();

  Comment = (function() {
    function Comment() {}

    return Comment;

  })();

  Result = (function() {
    function Result() {}

    return Result;

  })();

}).call(this);
