// Generated by CoffeeScript 2.3.2
//#
// Input to the [[#Collector]]
var Content;

Content = class Content {};

//#
// @property path
// @type String

//#
// @property file
// @type String

//#
// @property data
// @type String
