// Generated by CoffeeScript 2.3.1
(function() {
  //#
  // Generating options

  // It is built by a config file(crojsdoc.yaml) or command line arguments
  var Options;

  Options = class Options {};

  //#
// @property _project_dir
// @type String
// @private

//#
// @property types
// @type Object

//#
// @property _sources
// @type Array<String>

//#
// @property output_dir
// @type String

//#
// @property title
// @type String

//#
// @property quiet
// @type Boolean

//#
// @property files
// @type Boolean

//#
// @property _readme
// @type String
// @private

//#
// @property github
// @type String

}).call(this);
